### ISSUE TITLE
Define the type of a parser

### ISSUE THREAD

**Issue by mrange** [vlukash/fsharp-mentorship#1]
What is a natural signature for parser function?

```fsharp
type Parser<'T> = ...
```
What about error messages.

**Comment by vlukash** [comment]
Assuming that we're defining some specific parser (hardcoded) - takes some input to parse of type 'T and returns a tuple: result of parsing operation and remaining data that excludes parsed chunk of data

``` fsharp
type Parser<'T> = 'T -> (bool * 'T)
```

**Comment by vlukash** [comment]
To handle error messages we can return a tuple of 3 elements, like:

``` fsharp
type ErrorMessage = string
type Parser<'T> = 'T -> (bool * ErrorMessage * 'T)
```

Or as far as I know the better way is to create a choice type:

``` fsharp
type Result<'T> =
    | Success of 'T
    | Failure of string 
```

So this will automatically solve 2 problems - based on the return type of choice we can tell if operation was successful and we can provide error message if needed

``` fsharp
type Parser<'T> = 'T -> Result<'T>
```

**Comment by mrange** [comment]
A parser is a function that given a string produces a value so I would think that the input argument to the function should be a string.

I like the choice type (ie an ADT) but what is missing is the ability to chain two parsers together. A parser consumes part of a string and returns a value (if successful) but in order to make parsers chainable a parser function also returns the unconsumed string.

So I would think that the parser type should take a string as input and returns a value and the rest of the string on success.

To consider; creating substrings is expensive so we would like to avoid that.

PS: In F# `bool*'T` is most commonly represented as `'T option`.

**Comment by mrange** [comment]
Defining the fundamental type of a parser (or other constructs) I consider one of the most important steps. If it's done correctly the implementation will almost write itself.

**Comment by vlukash** [comment]
I think if we'll set input type as a string and leave ADT as return type than we'll get something like:

``` fsharp
type Result<'T> =
     | Success of 'T*string 
     | Failure of string 
```

``` fsharp
type Parser<'T> = string -> Result<'T>
```

Is that correct?

**Comment by mrange** [comment]
That parser definition will work but I will suggest two improvements:

``` fsharp
type Result<'T> =
     | Success of 'T*int 
     | Failure of string list*int
type Parser<'T> = string -> int -> Result<'T>
```
1. Instead a parser takes a string and a position. The results return an updated position. This allows us to avoid creating new substrings as this is an expensive operation.
2. When combining parsers we might have situations where we have multiple failures at a position. Therefore `string list`

**Comment by vlukash** [comment]
Oh, I see, thank you.

Now my question from issue #2 related to the char position is not relevant
